server:
  port: 7000
  http2:
    enabled: true

eureka:
  instance:
    hostname: 'localhost'
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

spring:
  config:
    import: configserver://
  application:
    name: 'gateway-service'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: user-service
          uri: http://localhost:9101/
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: reservation-service
          uri: http://localhost:9103/
          predicates:
            - Path=/reservation-service/**
          filters:
            - RewritePath=/reservation-service/(?<segment>.*),/$\{segment}
        - id: invoice-service
          uri: http://localhost:9104/
          predicates:
            - Path=/invoice-service/**
          filters:
            - RewritePath=/invoice-service/(?<segment>.*),/$\{segment}
        - id: admin-service
          uri: http://localhost:9102/
          predicates:
            - Path=/admin-service/**
          filters:
            - RewritePath=/admin-service/(?<segment>.*),/$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: "*"
